### ISSUE TITLE
error from useCkoCart not exported in useCko

### ISSUE THREAD

**Issue by CheStas** [vuestorefront/checkout-com#25]
an error that is set in useCkoCart.ts https://github.com/vuestorefront/checkout-com/blob/fbf0965ac70492b76cd831045ff6fbdaf121890f/src/useCkoCard.ts#L119
is not exported in useCko.ts
https://github.com/vuestorefront/checkout-com/blob/fbf0965ac70492b76cd831045ff6fbdaf121890f/src/useCko.ts#L42
it means that it's not possible to check and read an error if any happens in this method.

the error should be assigner to `useCko-error` https://github.com/vuestorefront/checkout-com/blob/fbf0965ac70492b76cd831045ff6fbdaf121890f/src/useCko.ts#L33

**Comment by Fifciu** [comment]
Please also update an unit test in new PR
